// Supabase client configuration
// This file sets up the Supabase client for database operations
// Note: This file is automatically generated. Do not edit it directly.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project configuration
// These values are specific to your Supabase project
const SUPABASE_URL = "https://cehywdlurwpolotdvkwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaHl3ZGx1cndwb2xvdGR2a3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTUxNjcsImV4cCI6MjA2OTQ3MTE2N30.lC_ckeZD7P6JuX03CmS-HGQKr3bCritDaCwUGehOEAA";

// Usage instructions:
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create and export the Supabase client instance
// This client is configured with authentication and session management
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use localStorage for session persistence
    storage: localStorage,
    // Automatically persist sessions across browser sessions
    persistSession: true,
    // Automatically refresh tokens when they expire
    autoRefreshToken: true,
  }
});