// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cehywdlurwpolotdvkwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaHl3ZGx1cndwb2xvdGR2a3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTUxNjcsImV4cCI6MjA2OTQ3MTE2N30.lC_ckeZD7P6JuX03CmS-HGQKr3bCritDaCwUGehOEAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});